
####################################
#### Define notification types #####
####################################
services:
    phpbbgallery.core.notification.image_for_approval:
        class: phpbbgallery\core\notification\events\phpbbgallery_image_for_approval
        shared: false # scope MUST be prototype for this to work!
        arguments:
            - '@user_loader'
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }
    phpbbgallery.core.notification.image_approved:
        class: phpbbgallery\core\notification\events\phpbbgallery_image_approved
        shared: false # scope MUST be prototype for this to work!
        arguments:
            - '@user_loader'
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }
    phpbbgallery.core.notification.new_image:
        class: phpbbgallery\core\notification\events\phpbbgallery_new_image
        shared: false # scope MUST be prototype for this to work!
        arguments:
            - '@user_loader'
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }
    phpbbgallery.core.notification.new_comment:
        class: phpbbgallery\core\notification\events\phpbbgallery_new_comment
        shared: false # scope MUST be prototype for this to work!
        arguments:
            - '@user_loader'
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }
    phpbbgallery.core.notification.new_report:
        class: phpbbgallery\core\notification\events\phpbbgallery_new_report
        shared: false # scope MUST be prototype for this to work!
        arguments:
            - '@user_loader'
            - '@dbal.conn'
            - '@cache.driver'
            - '@user'
            - '@auth'
            - '@config'
            - '@controller.helper'
            - '%core.root_path%'
            - '%core.php_ext%'
            - '%tables.notification_types%'
            - '%tables.notifications%'
            - '%tables.user_notifications%'
        tags:
            - { name: notification.type }
