parameters:
    phpbbgallery.core.file.source: %core.root_path%files/phpbbgallery/core/source/
    phpbbgallery.core.file.medium: %core.root_path%files/phpbbgallery/core/medium/
    phpbbgallery.core.file.mini: %core.root_path%files/phpbbgallery/core/mini/
    phpbbgallery.core.file.watermark: %core.root_path%ext/phpbbgallery/core/images/watermark.png

    tables.phpbbgallery.albums: %core.table_prefix%gallery_albums
    tables.phpbbgallery.contests: %core.table_prefix%gallery_contests
    tables.phpbbgallery.images: %core.table_prefix%gallery_images
    tables.phpbbgallery.moderators: %core.table_prefix%gallery_modscache
    tables.phpbbgallery.permissions: %core.table_prefix%gallery_permissions
    tables.phpbbgallery.roles: %core.table_prefix%gallery_roles
    tables.phpbbgallery.tracking: %core.table_prefix%gallery_albums_track
    tables.phpbbgallery.users: %core.table_prefix%gallery_users
    tables.phpbbgallery.comments: %core.table_prefix%gallery_comments
    tables.phpbbgallery.reports: %core.table_prefix%gallery_reports

services:
    phpbbgallery.core.album:
        class: phpbbgallery\core\album\album
    phpbbgallery.core.misc:
        class: phpbbgallery\core\misc
    phpbbgallery.core.album.display:
        class: phpbbgallery\core\album\display
        arguments:
            - @auth
            - @config
            - @controller.helper
            - @dbal.conn
            - @pagination
            - @request
            - @template
            - @user
            - @phpbbgallery.core.auth
            - @phpbbgallery.core.user
            - @phpbbgallery.core.misc
            - %core.root_path%
            - %core.php_ext%
            - %tables.phpbbgallery.albums%
            - %tables.phpbbgallery.contests%
            - %tables.phpbbgallery.moderators%
            - %tables.phpbbgallery.tracking%
    phpbbgallery.core.album.loader:
        class: phpbbgallery\core\album\loader
        arguments:
            - @dbal.conn
            - @user
            - %tables.phpbbgallery.albums%
    phpbbgallery.core.auth:
        class: phpbbgallery\core\auth\auth
        arguments:
            - @phpbbgallery.core.cache
            - @dbal.conn
            - @phpbbgallery.core.user
            - %tables.phpbbgallery.permissions%
            - %tables.phpbbgallery.roles%
            - %tables.phpbbgallery.users%
    phpbbgallery.core.auth.level:
        class: phpbbgallery\core\auth\level
        arguments:
            - @phpbbgallery.core.auth
            - @config
            - @template
            - @user
    phpbbgallery.core.cache:
        class: phpbbgallery\core\cache
        arguments:
            - @cache
            - @dbal.conn
    phpbbgallery.core.file.tool:
        class: phpbbgallery\core\file\file
        arguments:
            - 2
    phpbbgallery.core.image:
        class: phpbbgallery\core\image\image
        arguments:
            - @dbal.conn
            - @user
            - @phpbbgallery.core.auth
            - @phpbbgallery.core.album
            - @phpbbgallery.core.config
            - @controller.helper
            - %tables.phpbbgallery.images%
    phpbbgallery.core.listener:
        class: phpbbgallery\core\event\main_listener
        arguments:
            - @controller.helper
            - @template
            - @user
            - %core.php_ext%
        tags:
            - { name: event.listener }
    phpbbgallery.core.user:
        class: phpbbgallery\core\user
        arguments:
            - @dbal.conn
            - @dispatcher
            - %tables.phpbbgallery.users%
    phpbbgallery.core.controller.upload:
        class: phpbbgallery\core\controller\upload
        arguments:
            - @request
            - @dbal.conn
            - @user
            - @template
            - @phpbbgallery.core.album
            - @phpbbgallery.core.misc
            - @phpbbgallery.core.auth
            - @phpbbgallery.core.album.display
            - @controller.helper
            - @phpbbgallery.core.config
            - @phpbbgallery.core.user
            - @phpbbgallery.core.image
            - %tables.phpbbgallery.images%
    phpbbgallery.core.controller.album:
        class: phpbbgallery\core\controller\album
        arguments:
            - @config
            - @controller.helper
            - @dbal.conn
            - @pagination
            - @template
            - @user
            - @phpbbgallery.core.album.display
            - @phpbbgallery.core.album.loader
            - @phpbbgallery.core.auth
            - @phpbbgallery.core.auth.level
            - %tables.phpbbgallery.images%
    phpbbgallery.core.controller.file:
        class: phpbbgallery\core\controller\file
        arguments:
            - @config
            - @dbal.conn
            - @user
            - @phpbbgallery.core.auth
            - @phpbbgallery.core.user
            - @phpbbgallery.core.file.tool
            - %phpbbgallery.core.file.source%
            - %phpbbgallery.core.file.medium%
            - %phpbbgallery.core.file.mini%
            - %phpbbgallery.core.file.watermark%
            - %tables.phpbbgallery.albums%
            - %tables.phpbbgallery.images%
    phpbbgallery.core.controller.image:
        class: phpbbgallery\core\controller\image
        arguments:
            - @request
            - @auth
            - @config
            - @controller.helper
            - @dbal.conn
            - @dispatcher
            - @pagination
            - @template
            - @user
            - @phpbbgallery.core.album.display
            - @phpbbgallery.core.album.loader
            - @phpbbgallery.core.album
            - @phpbbgallery.core.image
            - @phpbbgallery.core.auth
            - @phpbbgallery.core.user
            - @phpbbgallery.core.config
            - @phpbbgallery.core.auth.level
            - @phpbbgallery.core.url
            - @phpbbgallery.core.misc
            - @phpbbgallery.core.comment
            - @phpbbgallery.core.report
            - %tables.phpbbgallery.albums%
            - %tables.phpbbgallery.images%
            - %tables.phpbbgallery.users%
            - %tables.phpbbgallery.comments%
            - %core.root_path%
            - %core.php_ext%
    phpbbgallery.core.controller.index:
        class: phpbbgallery\core\controller\index
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @controller.helper
            - @phpbbgallery.core.album.display
            - @phpbbgallery.core.config
            - @phpbbgallery.core.auth
            - @phpbbgallery.core.search
            - @pagination
            - @phpbbgallery.core.user
            - @phpbbgallery.core.image
            - %core.root_path%
            - %core.php_ext%
    phpbbgallery.core.controller.search:
        class: phpbbgallery\core\controller\search
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @pagination
            - @request
            - @template
            - @user
            - @controller.helper
            - @phpbbgallery.core.album.display
            - @phpbbgallery.core.config
            - @phpbbgallery.core.auth
            - @phpbbgallery.core.album
            - @phpbbgallery.core.image
            - @phpbbgallery.core.url
            - @phpbbgallery.core.search
            - %tables.phpbbgallery.images%
            - %tables.phpbbgallery.albums%
            - %tables.phpbbgallery.comments%
            - %core.root_path%
            - %core.php_ext%
    phpbbgallery.core.controller.comment:
        class: phpbbgallery\core\controller\comment
        arguments:
            - @dbal.conn
            - @user
            - @auth
            - @config
            - @template
            - @request
            - @controller.helper
            - @phpbbgallery.core.image
            - @phpbbgallery.core.album.loader
            - @phpbbgallery.core.album
            - @phpbbgallery.core.album.display
            - @phpbbgallery.core.url
            - @phpbbgallery.core.auth
            - @phpbbgallery.core.config
            - @phpbbgallery.core.misc
            - @phpbbgallery.core.comment
            - @phpbbgallery.core.user
            - %tables.phpbbgallery.comments%
            - %core.root_path%
            - %core.php_ext%
    phpbbgallery.core.controller.moderate:
        class: phpbbgallery\core\controller\moderate
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @controller.helper
            - @phpbbgallery.core.album.display
            - @phpbbgallery.core.moderate
            - @phpbbgallery.core.auth
            - @phpbbgallery.core.misc
            - @phpbbgallery.core.album
            - @phpbbgallery.core.image
            - %core.root_path%
            - %core.php_ext%
    phpbbgallery.core.config:
        class: phpbbgallery\core\config
        arguments:
            - @config
    phpbbgallery.core.report:
        class: phpbbgallery\core\report
    phpbbgallery.core.comment:
        class: phpbbgallery\core\comment
        arguments:
            - @user
            - @phpbbgallery.core.config
            - @phpbbgallery.core.auth
            - @phpbbgallery.core.image
            - @phpbbgallery.core.album
    phpbbgallery.core.url:
        class: phpbbgallery\core\url
        arguments:
            - %core.root_path%
            - %core.php_ext%
    phpbbgallery.core.moderate:
        class: phpbbgallery\core\moderate
        arguments:
            - @dbal.conn
            - @template
            - @controller.helper
            - @user
            - @user_loader
            - @phpbbgallery.core.album
            - @phpbbgallery.core.auth
            - %tables.phpbbgallery.images%
            - %tables.phpbbgallery.reports%
    phpbbgallery.core.search:
        class: phpbbgallery\core\search
        arguments:
            - @auth
            - @config
            - @dbal.conn
            - @request
            - @template
            - @user
            - @controller.helper
            - @phpbbgallery.core.album.display
            - @phpbbgallery.core.config
            - @phpbbgallery.core.auth
            - @phpbbgallery.core.album
            - @phpbbgallery.core.image
            - @phpbbgallery.core.url
            - %tables.phpbbgallery.images%
            - %tables.phpbbgallery.albums%
            - %tables.phpbbgallery.comments%
            - %core.root_path%
            - %core.php_ext%