# .coveralls.yml configuration

# for php-coveralls
src_dir: ../
service_name: trvis-ci
coverage_clover: /home/travis/build/satanasov/phpBB3/phpBB/ext/phpbbgallery/logs/clover.xml
json_path: /home/travis/build/satanasov/phpBB3/phpBB/ext/phpbbgallery/logs/coveralls-upload.json